name: Main Workflow (Python)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

jobs:
  Main-Job-Python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run
        run: python main.py
        env:
          VKTOKEN: ${{ secrets.VKTOKEN  }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build